### ISSUE TITLE
Doesn't work on Linux Chrome

### ISSUE THREAD

**Issue by emnh** [emnh/rts-reasonml#1]
inoryy 08:06AM
.Offscreen-For-WebGL-0x8e47e0bec00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: uniform buffers : buffer or buffer range not large enough at index 0

**Comment by emnh** [comment]
Fixed.

**Comment by Yugloocamai** [comment]
??? explain?

**Comment by emnh** [comment]
@Yugloocamai Do you still have problems with the demo on Linux Chrome? Please provide version and details from JS console if you can and reopen the issue if so.
