### ISSUE TITLE
Doesn't work on Mac OS X

### ISSUE THREAD

**Issue by emnh** [emnh/rts-reasonml#11]
Report 1:
bsansouci - Today at 5:22 AM
Hey I'm getting WebGL2Util-Rts.WebGL2Exception,40,missing extension EXT_color_buffer_half_float in the console and nothing's drawing on screen (on safari, osx)

Report 2:
Was no error in the JS console :/
 Mac + Chrome
 Ser Waves: 0 / waves2: 0 etc. (alle på 0) og en svart kontroll på høyresiden som eg kan utvide og klikke i, uten funksjon.

Report 2 supported WebGL1 extensions:
ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_disjoint_timer_query
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context

WebGL2 extensions:
EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context

https://pastebin.com/agXipejF

https://imgur.com/a/HegVb

**Comment by emnh** [comment]
Should work now. Added fallback to WebGL 1 for other platforms than Windows. Can anyone confirm?

**Comment by petetnt** [comment]
Works for me with Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by emnh** [comment]
Thanks! 👍
